kind: ConfigMap
apiVersion: v1
metadata:
   name: hive-metastore-config
   namespace: trino
data:
   metastore-site.xml: |-
      <configuration>
         <property>
            <name>metastore.task.threads.always</name>
            <value>org.apache.hadoop.hive.metastore.events.EventCleanerTask</value>
         </property>
         <property>
            <name>metastore.expression.proxy</name>
            <value>org.apache.hadoop.hive.metastore.DefaultPartitionExpressionProxy</value>
         </property>
         <property>
            <name>javax.jdo.option.ConnectionDriverName</name>
            <value>com.mysql.jdbc.Driver</value>
         </property>
         <property>
            <name>javax.jdo.option.ConnectionURL</name>
            <value>jdbc:mysql://mysql-service.trino.svc.cluster.local:3306/metastore_db?useSSL=false&amp;allowPublicKeyRetrieval=true</value>
         </property>
         <property>
            <name>javax.jdo.option.ConnectionUserName</name>
            <value>root</value>
         </property>
         <property>
            <name>javax.jdo.option.ConnectionPassword</name>
            <value>tes1234</value>
         </property>
         <property>
            <name>metastore.warehouse.dir</name>
            <value>s3a://ai-dev-trino-01/trino-warehouse/</value>
         </property>
         <property>
            <name>metastore.thrift.port</name>
            <value>9083</value>
         </property>
      </configuration>
