apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: trino
  labels:
    app: mysql
spec:
  serviceName: mysql
  minReadySeconds: 10
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.4
          imagePullPolicy: Always
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "test1234"
            - name: explicit_defaults_for_timestamp
              value: "1"
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mysql-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi # 필요한 스토리지 크기
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: trino
  labels:
    app: mysql
spec:
  ports:
    - port: 3306
      name: mysql
  clusterIP: None
  selector:
    app: mysql
